name: billblaze
description: A new Flutter project.
publish_to: 'none'  # Remove this line if you intend to publish your package.

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  location: any
  permission_handler: any
  anitex: ^3.0.1
  cloud_firestore: 
  firebase_core: ^2.25.4 
  firebase_auth: ^4.17.5 
  google_sign_in: ^6.2.1
  provider: any
  google_fonts: ^4.0.3
  flutter_riverpod: ^2.3.6
  flutter_hooks: ^0.19.0
  #
  expandable_menu: ^0.0.5
  #sketchy
  material_table_view: ^4.0.2
  iconsax_plus: ^1.0.0
  #sketchy
  # playable_toolbar_flutter: ^0.0.2
  flutter_adaptive_layout: ^1.0.2
  #comment for web
  google_sign_in_all_platforms: ^0.0.4
  simple_animated_button: ^0.0.9
  animated_text_kit: ^4.2.2
  fl_chart: ^0.68.0
  flutter_balloon_slider: ^0.1.1
  appinio_swiper: ^2.1.1
  uuid: ^4.4.0
  flutter_hsvcolor_picker: ^1.5.1
  pdf: ^3.10.8
  printing: ^5.12.0
  # ffi: ^2.1.2
  # http: ^1.2.1
  # image: ^4.2.0
  # js: ^0.7.1
  # meta: ^1.15.0
  # plugin_platform_interface: ^2.1.8
  # 
  animate_do: ^3.3.4
  crypto: ^3.0.3
  platform: ^3.1.5
  curved_navigation_bar: ^1.0.6
  # appflowy_board: ^0.1.2
  # fleather: ^1.15.0+1
  # keyboard_actions: ^4.2.0
  flutter_quill: ^9.4.0
  animated_custom_dropdown: ^3.1.1
  flutter_tabler_icons: ^1.31.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
