// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9vdkftBdUb17jTmeH0ixW5ISZF3ub7oY',
    appId: '1:32563284353:web:972e556dba54b9c65e4080',
    messagingSenderId: '32563284353',
    projectId: 'billblazex',
    authDomain: 'billblazex.firebaseapp.com',
    storageBucket: 'billblazex.appspot.com',
    measurementId: 'G-NK81YE23J7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlVf-tYlZghCCSAOd96mnvm24j7TqsAYM',
    appId: '1:32563284353:android:87b8da54a9723d455e4080',
    messagingSenderId: '32563284353',
    projectId: 'billblazex',
    storageBucket: 'billblazex.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkHjvGpKsECdpXZa6SqrDncwUS_KKsU48',
    appId: '1:32563284353:ios:987fa0383475fe265e4080',
    messagingSenderId: '32563284353',
    projectId: 'billblazex',
    storageBucket: 'billblazex.appspot.com',
    androidClientId: '32563284353-0jr1lkaju8is8kh0qmlnjc11ngis15fa.apps.googleusercontent.com',
    iosClientId: '32563284353-1eoor25tiju57jscn3hu5b2svo1mhm45.apps.googleusercontent.com',
    iosBundleId: 'com.jepixo.billblaze',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkHjvGpKsECdpXZa6SqrDncwUS_KKsU48',
    appId: '1:32563284353:ios:987fa0383475fe265e4080',
    messagingSenderId: '32563284353',
    projectId: 'billblazex',
    storageBucket: 'billblazex.appspot.com',
    androidClientId: '32563284353-0jr1lkaju8is8kh0qmlnjc11ngis15fa.apps.googleusercontent.com',
    iosClientId: '32563284353-1eoor25tiju57jscn3hu5b2svo1mhm45.apps.googleusercontent.com',
    iosBundleId: 'com.jepixo.billblaze',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9vdkftBdUb17jTmeH0ixW5ISZF3ub7oY',
    appId: '1:32563284353:web:a8101d7745c338ea5e4080',
    messagingSenderId: '32563284353',
    projectId: 'billblazex',
    authDomain: 'billblazex.firebaseapp.com',
    storageBucket: 'billblazex.appspot.com',
    measurementId: 'G-KSFJBMEZ5B',
  );

}