// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:billblaze/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BiStatFunctionAdapter());
    registerAdapter(ColumnFunctionAdapter());
    registerAdapter(DocumentPropertiesBoxAdapter());
    registerAdapter(IndexPathAdapter());
    registerAdapter(InputBlockAdapter());
    registerAdapter(InputBlockFunctionAdapter());
    registerAdapter(ItemDecorationBoxAdapter());
    registerAdapter(LayoutModelAdapter());
    registerAdapter(RequiredTextAdapter());
    registerAdapter(SheetDecorationAdapter());
    registerAdapter(SheetFunctionAdapter());
    registerAdapter(SheetItemAdapter());
    registerAdapter(SheetListBoxAdapter());
    registerAdapter(SheetSizedItemAdapter());
    registerAdapter(SheetTableBoxAdapter());
    registerAdapter(SheetTableCellBoxAdapter());
    registerAdapter(SheetTableColumnBoxAdapter());
    registerAdapter(SheetTableRowBoxAdapter());
    registerAdapter(SheetTextBoxAdapter());
    registerAdapter(SuperDecorationBoxAdapter());
    registerAdapter(UidGeneratorFunctionAdapter());
    registerAdapter(UniStatFunctionAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BiStatFunctionAdapter());
    registerAdapter(ColumnFunctionAdapter());
    registerAdapter(DocumentPropertiesBoxAdapter());
    registerAdapter(IndexPathAdapter());
    registerAdapter(InputBlockAdapter());
    registerAdapter(InputBlockFunctionAdapter());
    registerAdapter(ItemDecorationBoxAdapter());
    registerAdapter(LayoutModelAdapter());
    registerAdapter(RequiredTextAdapter());
    registerAdapter(SheetDecorationAdapter());
    registerAdapter(SheetFunctionAdapter());
    registerAdapter(SheetItemAdapter());
    registerAdapter(SheetListBoxAdapter());
    registerAdapter(SheetSizedItemAdapter());
    registerAdapter(SheetTableBoxAdapter());
    registerAdapter(SheetTableCellBoxAdapter());
    registerAdapter(SheetTableColumnBoxAdapter());
    registerAdapter(SheetTableRowBoxAdapter());
    registerAdapter(SheetTextBoxAdapter());
    registerAdapter(SuperDecorationBoxAdapter());
    registerAdapter(UidGeneratorFunctionAdapter());
    registerAdapter(UniStatFunctionAdapter());
  }
}
